message:
  welcome: '"Welcome changedagainsdasdas"'
server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"